### PR TITLE
Ms sql version provider

### PR DESCRIPTION
**Pull request by generik0**
Candidate for Transactions that follows existing patterns

### CODE REVIEW

**Comment by canton7** [comment]
Thanks for putting this together.

I considered following this approach, but decided that, really, `IVersionProvider` shouldn't know anything about transactions at all - if someone were to use SimpleMigrations for migrating XML file schemas, for example, there's no concept of a transaction.

That's why I ended up putting it into `Migration<TDatabase>`, since that class knows about ADO.NET. This meant that `IVersionProvider` wasn't used for anything, and so could be removed, which simplifies things some more.

Can you think of a good reason why we should go with the approach of keeping `IVersionProvider` and extending it to take `TTransaction`, over the approach of getting rid of it entirely?

**Comment by generik0** [comment]
Cant think of much. Not really. I just tried to follow your design.

 

The only thing is considering the unit of work pattern.

Really all migrations should be 1 unit of work / transaction.

So if anything failes, it all fails.

With the single transaction approach I believe yhou changed to, there is a risk of VersionInfo not bein updated?

 

BR Rik

**Comment by canton7** [comment]
> Really all migrations should be 1 unit of work / transaction. So if anything failes, it all fails. With the single transaction approach I believe yhou changed to, there is a risk of VersionInfo not bein updated?

Fair point. 

Unfortunately I don't think some databases allow you to create tables (or maybe update them?) inside of a transaction, which is why I have the option to disable transactions for each migration. This means that I can't run all migrations inside a single transaction. I think running each migration in its own transaction is fine: they're run in a particular order.

However I agree that the migration and updating the version table should be run in a single transaction (if possible). I think the only way to do this is to add `TTransaction` to `IConnectionProvider`, as you've done here... 

I'll think about it over the weekend, then take a look at it again early next week.

**Comment by canton7** [comment]
No, I want to keep this open, as I will probably use your `IConnectionProvider` work.

**Comment by canton7** [comment]
Closing as I've implemented an alternative

**Comment by generik0** [comment]
Great :-)

**Pull request closed without merging**
