### PR TITLE
README.md: Fixed typo

### PR DESCRIPTION
**Pull request by perlun**

### CODE REVIEW

**Comment by canton7** [comment]
Oops, thanks!

**Comment by canton7** [comment]
Cherry-picked onto develop, since it was submitted as master, so closing it here.

**Comment by perlun** [comment]
> Cherry-picked onto develop, since it was submitted against master, so closing it here.

OK, great! (Didn't know there was a separate `develop` branch, I just edited the file on the GH web UI)

**Comment by canton7** [comment]
Yeah, I like to set master as the default branch, as it means that issues are closed when I do a new release and not before (among other things). However it does mean that PRs get send against master by default. It's only a few seconds' work to rebase them though...

**Pull request closed without merging**
