### PR TITLE
Added SchemaName property to PostgresqlDatabaseProvider

### PR DESCRIPTION
**Pull request by alirezajm**
Also schemas are automatically created if they don't exist.

### CODE REVIEW

**Comment by canton7** [comment]
Thanks!

I'm a bit nervous about trying to automatically create the schemas - in my experience, database permissions tend to be defined on the schema, and so if the schema doesn't exist SimpleMigrations is unlikely to have permission to do anything.

On the other hand, fly does automatic schema creation...

I think I'd be happier if the schema creation SQL was broken out into a different method. I'll experiment over the next few days, hopefully.

**Comment by alirezajm** [comment]
Exactly, and the worst thing that might happen is a permission denied message.

Yeah I think too it would be cleaner to put it in a different method, I wasn't sure where to put it so I just put it there. 😁

**Comment by canton7** [comment]
Apologies for the delay - I'm been waiting for NUnit to update their test adapter to work with .NET Core csproj-based projects.

It looks like that's finally working, so I can start working on this again.

**Comment by canton7** [comment]
I cherry-picked your second command, and did the "create schema" stuff in a slightly different way.

**Pull request closed without merging**
