### PR TITLE
Add direction to version info

### PR DESCRIPTION
**Pull request by Scott-Lyons**
Added new direction column to VersionInfo table to see more easily the direction of the migration.

Note: Tested mssql provider but not setup locally to test other providers.

### CODE REVIEW

**Comment by canton7** [comment]
If I merge this, I will break anyone currently using SimpleMigrations: the query to insert new rows into the VersionInfo table will fail.

Like it or not, we're stuck with the structure of VersionInfo, unless we decide to figure out a way to apply migrations to the tables backing the migrations....

**Comment by Scott-Lyons** [comment]
Good point. I see some sort of Inception joke here about who migrates the migrations.

**Comment by Scott-Lyons** [comment]
Would it be fair to add a further update to the prerequisites to check for the column and add if required? I've only got a minor requirement for this change so probably more worth figuring out a solution to changes to the VersionInfo before adding on top of it?

**Comment by canton7** [comment]
This general problem also affects #25, so I want to come up with a robust way to change the SchemaVersion table, rather than duplicating the "check if column X exists, if not, add it" logic for each and every database provider.

**Comment by Scott-Lyons** [comment]
I'll close this for now then

**Comment by canton7** [comment]
I would mind a PR which passes the migration direction to the database provider as a parameter (maybe we need to create an object containing all parameters and pass that, for forward compatibility), then people can use it in a custom database provider if they wish.

**Pull request closed without merging**
